# Generated by Django 4.2.4 on 2023-08-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patientinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('Hospital_code', models.IntegerField()),
                ('Hospital_type_code', models.CharField(max_length=200)),
                ('City_Code_Hospital', models.IntegerField()),
                ('Available_Extra_Rooms_in_Hospital', models.IntegerField()),
                ('Department', models.CharField(max_length=200)),
                ('Ward_Type', models.CharField(max_length=200)),
                ('Bed_Grade', models.IntegerField()),
                ('City_Code_Patient', models.IntegerField()),
                ('Type_of_Admission', models.CharField(max_length=200)),
                ('Severity_of_Illness', models.CharField(max_length=200)),
                ('Visitors_with_Patient', models.IntegerField()),
                ('Age', models.IntegerField()),
                ('Admission_Deposit', models.IntegerField()),
                ('count_id_patient', models.IntegerField()),
                ('count_id_patient_hospitalCode', models.IntegerField()),
                ('count_id_patient_wardfacilityCode', models.IntegerField()),
            ],
        ),
    ]
